// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SqlServerDataBase.Models;
using System;

namespace SqlServerDataBase.Migrations
{
    [DbContext(typeof(EventsDbContecst))]
    partial class EventsDbContecstModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SqlServerDataBase.Models.Task", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<DateTime>("End");

                    b.Property<string>("EndTimezone");

                    b.Property<bool>("IsAllDay");

                    b.Property<string>("RecurrenceException");

                    b.Property<int?>("RecurrenceID");

                    b.Property<string>("RecurrenceRule");

                    b.Property<DateTime>("Start");

                    b.Property<string>("StartTimezone");

                    b.Property<int?>("Task1TaskID");

                    b.Property<string>("Title");

                    b.HasKey("TaskID");

                    b.HasIndex("Task1TaskID");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("SqlServerDataBase.Models.Task", b =>
                {
                    b.HasOne("SqlServerDataBase.Models.Task", "Task1")
                        .WithMany("Tasks1")
                        .HasForeignKey("Task1TaskID");
                });
#pragma warning restore 612, 618
        }
    }
}
